#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Apr 25, 2025 10:36:39 AM CDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import ViewForCivilAI_GUI_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black'
_tabfg2 = 'white'
_bgmode = 'light'
_tabbg1 = '#d9d9d9'
_tabbg2 = 'gray40'

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return
    try:
        ViewForCivilAI_GUI_support.root.tk.call('source',
            os.path.join(_location, 'themes', 'default.tcl'))
    except:
        pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font="TkDefaultFont")
    if sys.platform == "win32":
        style.theme_use('winnative')
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1181x601+186+143")
        top.minsize(120, 1)
        top.maxsize(3204, 1131)
        top.resizable(1, 1)
        top.title("Toplevel 0")
        top.configure(background="#141a5a")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.Frame2 = tk.Frame(self.top)
        self.Frame2.place(relx=0.017, rely=0.667, relheight=0.321, relwidth=0.658)
        self.Frame2.configure(relief='groove', borderwidth="2",
                              background="#d9d9d9", highlightbackground="#d9d9d9",
                              highlightcolor="#000000")

        self.Frame5 = tk.Frame(self.Frame2)
        self.Frame5.place(relx=0.013, rely=0.052, relheight=0.927, relwidth=0.277)
        self.Frame5.configure(relief='groove', borderwidth="2",
                              background="#314567", highlightbackground="#d9d9d9",
                              highlightcolor="#000000")

        self.Label7 = tk.Label(self.Frame5)
        self.Label7.place(relx=0.051, rely=0.609, height=21, width=37)
        self.Label7.configure(activebackground="#d9d9d9", activeforeground="black",
                              anchor='w', background="#000000", compound='left',
                              disabledforeground="#a3a3a3",
                              font="-family {Segoe UI} -size 9",
                              foreground="#000000", highlightbackground="#d9d9d9",
                              highlightcolor="#000000")

        self.Label3 = tk.Label(self.Frame5)
        self.Label3.place(relx=0.256, rely=0.609, height=22, width=95)
        self.Label3.configure(activebackground="#d9d9d9", activeforeground="black",
                              anchor='w', background="#314567", compound='left',
                              disabledforeground="#a3a3a3",
                              font="-family {Arial} -size 12",
                              foreground="#ffffff", highlightbackground="#d9d9d9",
                              highlightcolor="#000000", text='Background')

        self.Label2 = tk.Label(self.Frame5)
        self.Label2.place(relx=0.256, rely=0.441, height=22, width=139)
        self.Label2.configure(activebackground="#d9d9d9", activeforeground="black",
                              anchor='w', background="#314567", compound='left',
                              disabledforeground="#a3a3a3",
                              font="-family {Arial} -size 12",
                              foreground="#ffffff", highlightbackground="#d9d9d9",
                              highlightcolor="#000000", text='Damaged Rooftop')

        self.Label1 = tk.Label(self.Frame5)
        self.Label1.place(relx=0.256, rely=0.279, height=23, width=154)
        self.Label1.configure(activebackground="#d9d9d9", activeforeground="black",
                              anchor='w', background="#314567", compound='left',
                              disabledforeground="#a3a3a3",
                              font="-family {Arial} -size 12",
                              foreground="#ffffff", highlightbackground="#d9d9d9",
                              highlightcolor="#000000", text='Undamaged Rooftop')

        self.Label4 = tk.Label(self.Frame5)
        self.Label4.place(relx=0.023, rely=0.045, height=32, width=80)
        self.Label4.configure(activebackground="#d9d9d9", activeforeground="black",
                              anchor='w', background="#314567", compound='left',
                              disabledforeground="#a3a3a3",
                              font="-family {Arial} -size 20",
                              foreground="#ffffff", highlightbackground="#d9d9d9",
                              highlightcolor="#000000", text='Key')

        self.Label6 = tk.Label(self.Frame5)
        self.Label6.place(relx=0.051, rely=0.441, height=21, width=37)
        self.Label6.configure(activebackground="#d9d9d9", activeforeground="black",
                              anchor='w', background="#fa3253", compound='left',
                              disabledforeground="#a3a3a3",
                              font="-family {Segoe UI} -size 9",
                              foreground="#000000", highlightbackground="#d9d9d9",
                              highlightcolor="#000000")

        self.Label5 = tk.Label(self.Frame5)
        self.Label5.place(relx=0.051, rely=0.279, height=21, width=37)
        self.Label5.configure(activebackground="#33ddff", activeforeground="black",
                              anchor='w', background="#33ddff", compound='left',
                              disabledforeground="#a3a3a3",
                              font="-family {Segoe UI} -size 9",
                              foreground="#000000", highlightbackground="#00ffff",
                              highlightcolor="#000000")

        self.DamagePercentageFrame = tk.Frame(self.Frame2)
        self.DamagePercentageFrame.place(relx=0.296, rely=0.052, relheight=0.927, relwidth=0.695)
        self.DamagePercentageFrame.configure(relief='groove', borderwidth="2",
                                             background="#314567", highlightbackground="#d9d9d9",
                                             highlightcolor="#000000")

        _style_code()

        self.ActualPercentageLabel = ttk.Label(self.DamagePercentageFrame)
        self.ActualPercentageLabel.place(relx=0.011, rely=0.279, height=36, width=230)
        self.ActualPercentageLabel.configure(background="#314567", foreground="#ffffff",
                                              font="-family {Arial} -size 20", relief="flat",
                                              text='Actual Percentage', compound='left')

        self.TLabel1 = ttk.Label(self.DamagePercentageFrame)
        self.TLabel1.place(relx=0.009, rely=0.011, height=46, width=259)
        self.TLabel1.configure(background="#314567", foreground="#ffffff",
                               font="-family {Arial} -size 20", relief="flat",
                               text='Damage Percentage:', compound='left')

        self.FolderFrame = tk.Frame(self.top)
        self.FolderFrame.place(relx=0.686, rely=0.1, relheight=0.88, relwidth=0.307)
        self.FolderFrame.configure(relief='groove', borderwidth="2",
                                   background="#314567", highlightbackground="#ffffff",
                                   highlightcolor="#000000")

        self.Label8 = tk.Label(self.FolderFrame)
        self.Label8.place(relx=0.022, rely=0.004, height=39, width=344)
        self.Label8.configure(activebackground="#314567", activeforeground="black",
                              anchor='w', background="#314567", compound='left',
                              disabledforeground="#a3a3a3",
                              font="-family {Arial} -size 12",
                              foreground="#ffffff", highlightbackground="#d9d9d9",
                              highlightcolor="#000000", text='+ Add Folder')

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.017, rely=0.017, relheight=0.632, relwidth=0.658)
        self.Frame1.configure(relief='groove', borderwidth="2",
                              background="#a5a8b8", highlightbackground="#d9d9d9",
                              highlightcolor="#000000")

        self.PicturesFromFolderFrame = tk.Frame(self.Frame1)
        self.PicturesFromFolderFrame.place(relx=0.077, rely=0.026, relheight=0.929, relwidth=0.848)
        self.PicturesFromFolderFrame.configure(relief='groove', borderwidth="2",
                                               background="#d9d9d9", highlightbackground="#d9d9d9",
                                               highlightcolor="#000000")

        self.MovePictureRightButton = tk.Button(self.Frame1)
        self.MovePictureRightButton.place(relx=0.952, rely=0.445, height=26, width=17)
        self.MovePictureRightButton.configure(activebackground="#d9d9d9",
                                               activeforeground="black", background="#d9d9d9",
                                               disabledforeground="#a3a3a3",
                                               font="-family {Segoe UI} -size 9",
                                               foreground="#000000",
                                               highlightbackground="#d9d9d9",
                                               highlightcolor="#000000", text='Button')

        self.MovePictureLeftButton = tk.Button(self.Frame1)
        self.MovePictureLeftButton.place(relx=0.024, rely=0.455, height=26, width=17)
        self.MovePictureLeftButton.configure(activebackground="#d9d9d9",
                                              activeforeground="black", background="#d9d9d9",
                                              disabledforeground="#a3a3a3",
                                              font="-family {Segoe UI} -size 9",
                                              foreground="#000000",
                                              highlightbackground="#d9d9d9",
                                              highlightcolor="#000000", text='Button')

        self.Label9 = tk.Label(self.top)
        self.Label9.place(relx=0.686, rely=0.017, height=45, width=284)
        self.Label9.configure(activebackground="#141a5a", activeforeground="#000000",
                              anchor='w', background="#141a5a", compound='left',
                              disabledforeground="#a3a3a3",
                              font="-family {Arial} -size 20",
                              foreground="#ffffff", highlightbackground="#d9d9d9",
                              highlightcolor="#000000", text='History')


    def get_top(self):
        return self.top

    def get_frame1(self):
        return self.Frame1

    def get_frame2(self):
        return self.Frame2

    def get_frame5(self):
        return self.Frame5

    def get_folder_frame(self):
        return self.FolderFrame

    def get_pictures_from_folder_frame(self):
        return self.PicturesFromFolderFrame

    def get_damage_percentage_frame(self):
        return self.DamagePercentageFrame

    def get_move_picture_left_button(self):
        return self.MovePictureLeftButton

    def get_move_picture_right_button(self):
        return self.MovePictureRightButton

    def get_label1(self):
        return self.Label1  # "Undamaged Rooftop"

    def get_label2(self):
        return self.Label2  # "Damaged Rooftop"

    def get_label3(self):
        return self.Label3  # "Background"

    def get_label4(self):
        return self.Label4  # "KEY:"

    def get_label5(self):
        return self.Label5  # color box

    def get_label6(self):
        return self.Label6  # color box

    def get_label7(self):
        return self.Label7  # color box

    def get_label8(self):
        return self.Label8  # "+ Add Folder"

    def get_label9(self):
        return self.Label9  # "HISTORY"

    def get_tlabel1(self):
        return self.TLabel1  # "Damage Percentage:"

    def get_actual_percentage_label(self):
        return self.ActualPercentageLabel

def start_up():
    ViewForCivilAI_GUI_support.main()

# if __name__ == '__main__':
#     ViewForCivilAI_GUI_support.main()
