#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Apr 22, 2025 06:17:49 PM CDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import ViewForCivilAI_GUI_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return		
    try: ViewForCivilAI_GUI_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')	
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
    
        top.geometry("1181x601+-1610+241")
        top.minsize(120, 1)
        top.maxsize(3204, 1131)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.Frame2 = tk.Frame(self.top)
        self.Frame2.place(relx=0.017, rely=0.667, relheight=0.321, relwidth=0.658)
        self.Frame2.configure(relief='groove', borderwidth="2", background="#d9d9d9", highlightbackground="#d9d9d9", highlightcolor="#000000")

        self.Frame5 = tk.Frame(self.Frame2)
        self.Frame5.place(relx=0.013, rely=0.052, relheight=0.927, relwidth=0.251)
        self.Frame5.configure(relief='groove', borderwidth="2", background="#d9d9d9", cursor="fleur", highlightbackground="#d9d9d9", highlightcolor="#000000")

        self.Label1 = tk.Label(self.Frame5)
        self.Label1.place(relx=0.359, rely=0.279, height=23, width=120)
        self.Label1.configure(activebackground="#d9d9d9", activeforeground="black", anchor='w', background="#d9d9d9", compound='left', disabledforeground="#a3a3a3", foreground="#000000", highlightbackground="#d9d9d9", highlightcolor="#000000", text='Undamaged Rooftop')

        self.Label2 = tk.Label(self.Frame5)
        self.Label2.place(relx=0.359, rely=0.441, height=22, width=108)
        self.Label2.configure(activebackground="#d9d9d9", activeforeground="black", anchor='w', background="#d9d9d9", compound='left', disabledforeground="#a3a3a3", foreground="#000000", highlightbackground="#d9d9d9", highlightcolor="#000000", text='Damaged Rooftop')

        self.Label3 = tk.Label(self.Frame5)
        self.Label3.place(relx=0.359, rely=0.609, height=22, width=77)
        self.Label3.configure(activebackground="#d9d9d9", activeforeground="black", anchor='w', background="#d9d9d9", compound='left', cursor="fleur", disabledforeground="#a3a3a3", foreground="#000000", highlightbackground="#d9d9d9", highlightcolor="#000000", text='Background')

        self.Label4 = tk.Label(self.Frame5)
        self.Label4.place(relx=0.021, rely=0.061, height=22, width=33)
        self.Label4.configure(activebackground="#d9d9d9", activeforeground="black", anchor='w', background="#d9d9d9", compound='left', disabledforeground="#a3a3a3", foreground="#000000", highlightbackground="#d9d9d9", highlightcolor="#000000", text='KEY:')

        self.Label5 = tk.Label(self.Frame5)
        self.Label5.place(relx=0.051, rely=0.279, height=21, width=34)
        self.Label5.configure(activebackground="#00ffff", activeforeground="black", anchor='w', background="#00ffff", compound='left', disabledforeground="#a3a3a3", foreground="#000000", highlightbackground="#00ffff", highlightcolor="#000000")

        self.Label6 = tk.Label(self.Frame5)
        self.Label6.place(relx=0.051, rely=0.441, height=21, width=34)
        self.Label6.configure(activebackground="#d9d9d9", activeforeground="black", anchor='w', background="#eb0214", compound='left', disabledforeground="#a3a3a3", foreground="#000000", highlightbackground="#d9d9d9", highlightcolor="#000000")

        self.Label7 = tk.Label(self.Frame5)
        self.Label7.place(relx=0.051, rely=0.609, height=21, width=34)
        self.Label7.configure(activebackground="#d9d9d9", activeforeground="black", anchor='w', background="#040000", compound='left', disabledforeground="#a3a3a3", foreground="#000000", highlightbackground="#d9d9d9", highlightcolor="#000000")

        self.DamagePercentageFrame = tk.Frame(self.Frame2)
        self.DamagePercentageFrame.place(relx=0.27, rely=0.052, relheight=0.927, relwidth=0.709)
        self.DamagePercentageFrame.configure(relief='groove', borderwidth="2", background="#d9d9d9", highlightbackground="#d9d9d9", highlightcolor="#000000")

        _style_code()
        self.TLabel1 = ttk.Label(self.DamagePercentageFrame)
        self.TLabel1.place(relx=0.036, rely=0.112, height=16, width=114)
        self.TLabel1.configure(font="TkDefaultFont", relief="flat", text='Damage Percentage:', compound='left')

        self.ActualPercentageLabel = ttk.Label(self.DamagePercentageFrame)
        self.ActualPercentageLabel.place(relx=0.254, rely=0.112, height=16, width=104)
        self.ActualPercentageLabel.configure(font="TkDefaultFont", relief="flat", text='Actual Percentage', compound='left', cursor="fleur")

        self.Label9 = tk.Label(self.top)
        self.Label9.place(relx=0.686, rely=0.033, height=21, width=284)
        self.Label9.configure(activebackground="#d9d9d9", activeforeground="black", anchor='w', background="#d9d9d9", compound='left', disabledforeground="#a3a3a3", foreground="#000000", highlightbackground="#d9d9d9", highlightcolor="#000000", text='HISTORY')

        self.FolderFrame = tk.Frame(self.top)
        self.FolderFrame.place(relx=0.686, rely=0.067, relheight=0.913, relwidth=0.307)
        self.FolderFrame.configure(relief='groove', borderwidth="2", background="#d9d9d9", highlightbackground="#d9d9d9", highlightcolor="#000000")

        self.Label8 = tk.Label(self.FolderFrame)
        self.Label8.place(relx=0.028, rely=0.016, height=20, width=344)
        self.Label8.configure(activebackground="#d9d9d9", activeforeground="black", anchor='w', background="#d9d9d9", compound='left', disabledforeground="#a3a3a3", foreground="#000000", highlightbackground="#d9d9d9", highlightcolor="#000000", text='+ Add Folder')

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.017, rely=0.022, relheight=0.634, relwidth=0.658)
        self.Frame1.configure(relief='groove', borderwidth="2", background="#d9d9d9", highlightbackground="#d9d9d9", highlightcolor="#000000")

        self.MovePictureLeftButton = tk.Button(self.Frame1)
        self.MovePictureLeftButton.place(relx=0.024, rely=0.457, height=26, width=17)
        self.MovePictureLeftButton.configure(activebackground="#d9d9d9", activeforeground="black", background="#d9d9d9", disabledforeground="#a3a3a3", font="-family {Segoe UI} -size 9", foreground="#000000", highlightbackground="#d9d9d9", highlightcolor="#000000", text='Button')

        self.MovePictureRightButton = tk.Button(self.Frame1)
        self.MovePictureRightButton.place(relx=0.952, rely=0.446, height=26, width=17)
        self.MovePictureRightButton.configure(activebackground="#d9d9d9", activeforeground="black", background="#d9d9d9", disabledforeground="#a3a3a3", font="-family {Segoe UI} -size 9", foreground="#000000", highlightbackground="#d9d9d9", highlightcolor="#000000", text='Button')

        self.PicturesFromFolderFrame = tk.Frame(self.Frame1)
        self.PicturesFromFolderFrame.place(relx=0.084, rely=0.047, relheight=0.929, relwidth=0.848)
        self.PicturesFromFolderFrame.configure(relief='groove', borderwidth="2", background="#d9d9d9", highlightbackground="#d9d9d9", highlightcolor="#000000")

    def get_top(self):
        return self.top

    def get_frame1(self):
        return self.Frame1

    def get_frame2(self):
        return self.Frame2

    def get_frame5(self):
        return self.Frame5

    def get_folder_frame(self):
        return self.FolderFrame

    def get_pictures_from_folder_frame(self):
        return self.PicturesFromFolderFrame

    def get_damage_percentage_frame(self):
        return self.DamagePercentageFrame

    def get_move_picture_left_button(self):
        return self.MovePictureLeftButton

    def get_move_picture_right_button(self):
        return self.MovePictureRightButton

    def get_label1(self):
        return self.Label1  # "Undamaged Rooftop"

    def get_label2(self):
        return self.Label2  # "Damaged Rooftop"

    def get_label3(self):
        return self.Label3  # "Background"

    def get_label4(self):
        return self.Label4  # "KEY:"

    def get_label5(self):
        return self.Label5  # color box

    def get_label6(self):
        return self.Label6  # color box

    def get_label7(self):
        return self.Label7  # color box

    def get_label8(self):
        return self.Label8  # "+ Add Folder"

    def get_label9(self):
        return self.Label9  # "HISTORY"

    def get_tlabel1(self):
        return self.TLabel1  # "Damage Percentage:"

    def get_actual_percentage_label(self):
        return self.ActualPercentageLabel

def start_up():
    ViewForCivilAI_GUI_support.main()

# if __name__ == '__main__':
#     ViewForCivilAI_GUI_support.main()
