#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Apr 22, 2025 06:14:25 PM CDT  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 1181x601+-1610+241
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3204 1131
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame "$top.fra48" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 145 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 395 
    vTcl:DefineAlias "$top.fra48" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra48
    frame "$site_3_0.fra54" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 180 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 195 
    vTcl:DefineAlias "$site_3_0.fra54" "Frame5" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra54
    label "$site_4_0.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Undamaged Rooftop" 
    vTcl:DefineAlias "$site_4_0.lab47" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Damaged Rooftop" 
    vTcl:DefineAlias "$site_4_0.lab48" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Background" 
    vTcl:DefineAlias "$site_4_0.lab49" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "KEY:" 
    vTcl:DefineAlias "$site_4_0.lab50" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab51" \
        -activebackground #00ffff -activeforeground black -anchor w \
        -background #00ffff -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #00ffff -highlightcolor #000000 
    vTcl:DefineAlias "$site_4_0.lab51" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #eb0214 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 
    vTcl:DefineAlias "$site_4_0.lab52" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #040000 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 
    vTcl:DefineAlias "$site_4_0.lab53" "Label7" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab47 \
        -in $site_4_0 -x 0 -relx 0.359 -y 0 -rely 0.278 -width 0 \
        -relwidth 0.615 -height 0 -relheight 0.128 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab48 \
        -in $site_4_0 -x 0 -relx 0.359 -y 0 -rely 0.444 -width 0 \
        -relwidth 0.554 -height 0 -relheight 0.122 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab49 \
        -in $site_4_0 -x 0 -relx 0.359 -y 0 -rely 0.611 -width 0 \
        -relwidth 0.395 -height 0 -relheight 0.122 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab50 \
        -in $site_4_0 -x 0 -relx 0.021 -y 0 -rely 0.061 -width 0 \
        -relwidth 0.169 -height 0 -relheight 0.122 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab51 \
        -in $site_4_0 -x 0 -relx 0.051 -y 0 -rely 0.278 -width 0 \
        -relwidth 0.174 -height 0 -relheight 0.117 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab52 \
        -in $site_4_0 -x 0 -relx 0.051 -y 0 -rely 0.444 -width 0 \
        -relwidth 0.174 -height 0 -relheight 0.117 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab53 \
        -in $site_4_0 -x 0 -relx 0.051 -y 0 -rely 0.611 -width 0 \
        -relwidth 0.174 -height 0 -relheight 0.117 -anchor nw \
        -bordermode ignore 
    frame "$site_3_0.fra55" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 180 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 551 
    vTcl:DefineAlias "$site_3_0.fra55" "DamagePercentageFrame" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra55
    ttk::label "$site_4_0.tLa54" \
        -font "-family {Segoe UI} -size 9" -relief flat \
        -text "Damage Percentage:" -compound left 
    vTcl:DefineAlias "$site_4_0.tLa54" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_4_0.tLa55" \
        -font "-family {Segoe UI} -size 9" -relief flat \
        -text "Actual Percentage" -compound left 
    vTcl:DefineAlias "$site_4_0.tLa55" "ActualPercentageLabel" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.tLa54 \
        -in $site_4_0 -x 0 -relx 0.036 -y 0 -rely 0.109 -width 0 \
        -relwidth 0.207 -height 0 -relheight 0.091 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tLa55 \
        -in $site_4_0 -x 0 -relx 0.254 -y 0 -rely 0.112 -width 0 \
        -relwidth 0.189 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra54 \
        -in $site_3_0 -x 0 -relx 0.013 -y 0 -rely 0.052 -width 0 \
        -relwidth 0.251 -height 0 -relheight 0.928 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra55 \
        -in $site_3_0 -x 0 -relx 0.27 -y 0 -rely 0.052 -width 0 \
        -relwidth 0.709 -height 0 -relheight 0.927 -anchor nw \
        -bordermode ignore 
    label "$top.lab57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "HISTORY" 
    vTcl:DefineAlias "$top.lab57" "Label9" vTcl:WidgetProc "Toplevel1" 1
    frame "$top.fra49" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 921 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 590 
    vTcl:DefineAlias "$top.fra49" "FolderFrame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra49
    label "$site_3_0.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "+ Add Folder" 
    vTcl:DefineAlias "$site_3_0.lab56" "Label8" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.028 -y 0 -rely 0.017 -width 0 \
        -relwidth 0.948 -height 0 -relheight 0.036 -anchor nw \
        -bordermode ignore 
    frame "$top.fra47" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 285 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 395 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    button "$site_3_0.but52" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Button" 
    vTcl:DefineAlias "$site_3_0.but52" "MovePictureLeftButton" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but53" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Button" 
    vTcl:DefineAlias "$site_3_0.but53" "MovePictureRightButton" vTcl:WidgetProc "Toplevel1" 1
    frame "$site_3_0.fra50" \
        -borderwidth 2 -relief groove -background #d9d9d9 -height 265 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 335 
    vTcl:DefineAlias "$site_3_0.fra50" "PicturesFromFolderFrame" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.025 -y 0 -rely 0.456 -width 17 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 0 -relx 0.952 -y 0 -rely 0.446 -width 17 -relwidth 0 \
        -height 26 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra50 \
        -in $site_3_0 -x 0 -relx 0.084 -y 0 -rely 0.047 -width 0 \
        -relwidth 0.848 -height 0 -relheight 0.929 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra48 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.667 -width 0 -relwidth 0.658 \
        -height 0 -relheight 0.322 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.686 -y 0 -rely 0.033 -width 0 -relwidth 0.24 \
        -height 0 -relheight 0.035 -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 0 -relx 0.686 -y 0 -rely 0.067 -width 0 -relwidth 0.307 \
        -height 0 -relheight 0.913 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.022 -width 0 -relwidth 0.658 \
        -height 0 -relheight 0.633 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

